### PR TITLE
(refactor) Bring the codebase up to date

### PR DESCRIPTION
**Pull request by jroesch**
The code has not been actively patched in ~2 months and both Iron and Rust have changed
quite a bit. This is my first round of refactors and everything appears to be green.
The major differences are the handling of Middleware in Iron. I changed the old
`Middleware` `impl` to one for `BeforeMiddleware`. The rest of the changes are centered
around making sure all tests can run, and are green. I have tried my best to not change any semantics but being human I am sure there are some mistakes, code review much appreciated!

### CODE REVIEW

**Comment by IslandUsurper** [comment]
Alas, time marches on, and these changes are no longer sufficient to bring session up to speed. The main changes I have found are the way function/closure-type arguments are declared (`mutator` in SessionStore), `typemap` is accessed through the `iron` crate now, and `typemap::Assoc` doesn't exist any more.

That last one is the worst because `typemap::Key` and `RequestSession` don't take type parameters, but `Session<K, V>` does. Rustc complains if I try to do the obvious thing:
```rust
impl<K: 'static, V: 'static> typemap::Key for RequestSession { type Value = session::Session<K, V>; }
```

**Comment by thorbenk** [comment]
@IslandUsurper can you post your current changeset?

**Comment by IslandUsurper** [comment]
@thorbenk, I've pushed it to [my fork](https://github.com/IslandUsurper/session/tree/refactor/iron). It's based off this PR, so I can make a new one based on this repo or @jroesch's.

**Comment by BruceL33t** [comment]
I tried to fix the error @IslandUsurper mentioned above - unfortunately without luck. Would be awesome if someone look into a solution. :-)

**Pull request merged**
